### PR TITLE
Added support for html to markdown conversion

### PR DESCRIPTION
**Pull request by mattiascibien**
Added html2markdown conversion using html2markdown from nuget.

This modification unfortunately implied upgrading the project to .NET 4.5 and since I am not sure on how you wish to manage this I am open about discussion.

The conversion is fairly perfect using https://github.com/baynezy/Html2Markdown.

### CODE REVIEW

**Comment by mattiascibien** [comment]
6cff767 and  287f28c where not actually intended to be here. I'll try to fix this and remove them.

**Comment by theaob** [comment]
I'm looking into this. Might merge after adding "blockquote" tags to the library though.

**Comment by mattiascibien** [comment]
I am actually forking the lib repository to investigate further with the developer of the library to add blockquote. Seems quite easy to implement.

**Comment by theaob** [comment]
I did sent a pull request. It also worked with .Net 4.0 but I didn't get the lib via nuget. I'll test it after the library is updated.

**Comment by mattiascibien** [comment]
I did the same thing at your time. https://github.com/baynezy/Html2Markdown/pulls/2. I have closed mine.

**Comment by mattiascibien** [comment]
Any news on this? It's been 6 months since it has been opened

**Comment by theaob** [comment]
Sorry, I forgot to trace back the pull requests for a while. They merged my request so there is no reason not to merge your request. Thanks.

**Pull request merged**
